import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Header from '@/components/Header'
import { Navbar } from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className='min-w-[600px] bg-gradient-radial from-lime-200 via-gray-200 to-teal-200 gradient-radial'>
        {/* <Header username='tariq'/> */}
        <Navbar/>
        <div>
        {children}
        </div>
        </body>
    </html>
    </ClerkProvider>
  )
}
